# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  name-server: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80 # RocketMQ Namesrv
  access-channel: CLOUD
  # Producer 配置项
  producer:
    group: GID_PRODUCER_GROUP_YUNAI_TEST # 生产者分组
    access-key: LTAI6QUzlSnOYnrF
    secret-key: Y2M7qrdZQn5wxL1PU3sGusTPpfdFVS
