spring:
  application:
    name: demo-application # 应用名

nacos:
  discovery:
    server-addr: 127.0.0.1:18848 # Nacos 服务器地址
    auto-register: true # 是否自动注册到 Nacos 中。默认为 false。
    namespace: # 使用的 Nacos 的命名空间，默认为 null。
    register:
      group-name: DEFAULT_GROUP # 使用的 Nacos 服务分组，默认为 DEFAULT_GROUP。
      cluster-name: cluster01 # 集群名，默认为空。
