spring:
  application:
    name: demo-consumer-application
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        demo01-input:
          destination: mqTestDefault # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
#          group: demo01-consumer-group-DEMO-TOPIC-01 # 消费者分组

server:
  port: ${random.int[10000,19999]} # 随机端口，方便启动多个消费者
