# Nacos 配置项，对应 NacosConfigProperties 配置类
nacos:
  config:
    server-addr: 127.0.0.1:18848 # Nacos 服务器地址
    data-id: example # 使用的 Nacos 配置集的 dataId
    type: YAML # 使用的 Nacos 配置集的配置格式
    bootstrap:
      enable: true # 是否开启 Nacos 配置预加载功能
